config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    registrations: "users/registrations"
  }

  namespace :admin do
    resources :categories

    resources :pages do
      member do
        get :editor
        patch :toggle_status
      end
    end

    get "dashboard", to: "dashboard#index"
    root to: "dashboard#index"
  end

  # Rutas para categorías y páginas personalizadas
  resources :categories, only: [ :show ]
  resources :pages, only: [ :show ]
  resources :tourism, only: [ :index ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
  head
    title = content_for(:title) || "Tepeapulco"
    meta name="viewport" content="width=device-width,initial-scale=1"
    meta name="apple-mobile-web-app-capable" content="yes"
    meta name="mobile-web-app-capable" content="yes"
    = csrf_meta_tags
    = csp_meta_tag

    = yield :head

    // Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!)
    //= tag.link rel: "manifest", href: pwa_manifest_path(format: :json)

    link rel="icon" href="/icon.png" type="image/png"
    link rel="icon" href="/icon.svg" type="image/svg+xml"
    link rel="apple-touch-icon" href="/icon.png"

    //# Includes all stylesheet files in app/assets/stylesheets
    = stylesheet_link_tag "tailwind", "data-turbo-track": "reload"
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_importmap_tags

  body.h-screen
    div class="min-h-full grid grid-rows-[auto_auto_1fr_auto]"
      header class="bg-gray-800 text-white py-4"
        div class="container mx-auto px-4"
          div class="flex justify-between items-center"
            = link_to root_url do 
              h1 class="text-3xl font-bold" Tepeapulco
            - if user_signed_in?
              div class="flex items-center"
                span.mr-2 = current_user.name
                - if current_user.admin?
                  = link_to "Admin", admin_root_path, class: "bg-red-600 text-white px-3 py-1 rounded mr-2 hover:bg-red-700"
                = link_to "Perfil", edit_user_registration_path, class: "bg-indigo-600 text-white px-3 py-1 rounded mr-2 hover:bg-indigo-700"
                = button_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "bg-gray-600 text-white px-3 py-1 rounded hover:bg-gray-700", form: { data: { turbo: false } }
            - else
              div
                = link_to "Iniciar sesión", new_user_session_path, class: "bg-indigo-600 text-white px-3 py-1 rounded mr-2 hover:bg-indigo-700"
                = link_to "Registrarse", new_user_registration_path, class: "bg-indigo-600 text-white px-3 py-1 rounded hover:bg-indigo-700"
          nav class="mt-2"
            ul class="flex justify-center"
              / - Category.featured.each do |category|
              li class="mx-2": a href=(tourism_index_path) class="hover:text-gray-300" Turismo
      
      .flash 
        - if notice
          p.notice.bg-green-100.border.border-green-400.text-green-700.px-4.py-3.rounded.relative.mb-4.mx-auto.container role="alert" = notice
        - if alert
          p.alert.bg-red-100.border.border-red-400.text-red-700.px-4.py-3.rounded.relative.mb-4.mx-auto.container role="alert" = alert
      
      main class="container mx-auto mt-8 p-5 flex"
        = yield
      footer class="bg-gray-800 text-white py-4 text-center"
        p &copy; 2025 Tepeapulco